[package]
name = "maden-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
heck = { workspace = true }
inventory = { workspace = true }
